import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readCatalogBundle } from "./catalog-utils.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const errors = [];
const warnings = [];
const jsFiles = [
  "bootstrap.js",
  "profiles.js",
  "interaction-model.js",
  "practice-catalog.js",
  "storage.js",
  "catalog-runtime.js",
  "text-ui.js",
  "score-ui.js",
  "app.js"
];
const publicBaseUrl = "https://random-echo.github.io/checklist-bdsm-test/";
const publicChecklistUrl = `${publicBaseUrl}checklist.html`;
const oldAccountPattern = new RegExp([
  ["cle", "ment", "fas", "quel"].join(""),
  ["cle", "ment", "fas", "quel"].join("-")
].join("|"), "i");
const forbiddenPersonalMarkers = [
  new RegExp(["google", "site", "verification"].join("-"), "i"),
  /C:\\Users\\/i,
  new RegExp(["mail", "to:"].join(""), "i"),
  /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i,
  oldAccountPattern
];

function fail(message) {
  errors.push(message);
}

function warn(message) {
  warnings.push(message);
}

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function exists(relativePath) {
  return fs.existsSync(path.join(root, relativePath));
}

function localHrefTarget(value) {
  const raw = String(value || "").trim();
  if (!raw || raw.startsWith("#") || /^[a-z][a-z0-9+.-]*:/i.test(raw)) return "";
  return raw.split(/[?#]/)[0];
}

const appText = read("app.js");
const version = appText.match(/APP_VERSION\s*=\s*["'](V\d+\.\d+(?:\.\d+)?)["']/)?.[1];
if (!version) fail("app.js: APP_VERSION introuvable.");

const packageJson = JSON.parse(read("package.json"));
function packageVersionMatches(siteVersion, packageVersion) {
  const bare = siteVersion.replace(/^V/i, "");
  return packageVersion === bare || packageVersion === `${bare}.0`;
}

if (version && !packageVersionMatches(version, packageJson.version)) {
  fail(`package.json: version ${packageJson.version} differente de ${version}.`);
}

for (const file of [
  "index.html",
  "checklist.html",
  "sitemap.xml",
  "robots.txt",
  "README.md",
  ...jsFiles
].filter(exists)) {
  const content = read(file);
  for (const marker of forbiddenPersonalMarkers) {
    if (marker.test(content)) fail(`${file}: marqueur personnel ou verification externe detecte.`);
  }
}

for (const htmlFile of ["index.html", "checklist.html"]) {
  const html = read(htmlFile);
  const expectedCanonical = htmlFile === "index.html" ? publicBaseUrl : publicChecklistUrl;

  for (const match of html.matchAll(/\b(?:src|href)=["']([^"']+)["']/g)) {
    const target = localHrefTarget(match[1]);
    if (target && !exists(target)) fail(`${htmlFile}: reference locale manquante: ${match[1]}`);
  }

  for (const match of html.matchAll(/[?&]v=([^"&#]+)/g)) {
    if (version && match[1] !== version) fail(`${htmlFile}: cache-buster ${match[1]} different de ${version}.`);
  }

  if (!html.includes(`<link rel="canonical" href="${expectedCanonical}"/>`)) {
    fail(`${htmlFile}: canonical manquant ou different de ${expectedCanonical}.`);
  }

  if (!html.includes(`<meta property="og:url" content="${expectedCanonical}"/>`)) {
    fail(`${htmlFile}: og:url manquant ou different de ${expectedCanonical}.`);
  }
}

const sitemap = read("sitemap.xml");
for (const expectedUrl of [publicBaseUrl, publicChecklistUrl]) {
  if (!sitemap.includes(`<loc>${expectedUrl}</loc>`)) fail(`sitemap.xml: URL manquante: ${expectedUrl}`);
}

if (exists("robots.txt")) {
  const robots = read("robots.txt");
  if (!robots.includes(`Sitemap: ${new URL("sitemap.xml", publicBaseUrl).href}`)) {
    fail("robots.txt: sitemap public manquant ou incorrect.");
  }
}

for (const jsFile of jsFiles) {
  try {
    new Function(read(jsFile));
  } catch (error) {
    fail(`${jsFile}: syntaxe JavaScript invalide: ${error.message}`);
  }
}

const css = read("app.css").replace(/\/\*[\s\S]*?\*\//g, "");
const opens = (css.match(/{/g) || []).length;
const closes = (css.match(/}/g) || []).length;
if (opens !== closes) fail(`app.css: accolades CSS desequilibrees (${opens} / ${closes}).`);

const requiredThemeTokens = [
  "--dominant-color",
  "--dominant-dark",
  "--dominant-soft",
  "--role-color",
  "--role-dark",
  "--role-soft",
  "--dom-role-color",
  "--dom-role-dark",
  "--dom-role-soft",
  "--sub-role-color",
  "--sub-role-dark",
  "--sub-role-soft"
];
for (const token of requiredThemeTokens) {
  if (!css.includes(token) && !appText.includes(token)) fail(`theme: variable couleur manquante: ${token}`);
}
if (/dataset\.dominantSide\s*=\s*["']["']/.test(appText)) {
  fail("app.js: data-dominant-side doit etre absent en edition, pas vide.");
}

const catalogText = read("practice-catalog.js");
if (!catalogText.startsWith("/* Generated by ")) {
  warn("practice-catalog.js: l'en-tete genere attendu est absent.");
}

try {
  const catalog = readCatalogBundle().catalog;
  const ids = new Set();
  const categories = new Set(Object.keys(catalog.categoryColors || {}));

  if (!Array.isArray(catalog.entities) || catalog.entities.length === 0) {
    fail("practice-catalog.js: aucune entree de catalogue.");
  }

  for (const entity of catalog.entities || []) {
    if (!entity?.id) fail("catalogue: entree sans id.");
    if (ids.has(entity.id)) fail(`catalogue: id duplique: ${entity.id}`);
    ids.add(entity.id);

    const scenarioBlocks = Object.values(entity.scenarios || {});
    if (!scenarioBlocks.length) fail(`catalogue ${entity.id}: aucun scenario.`);
    for (const block of scenarioBlocks) {
      if (!block?.category) fail(`catalogue ${entity.id}: scenario sans categorie.`);
      else if (!categories.has(block.category)) fail(`catalogue ${entity.id}: couleur manquante pour "${block.category}".`);
      if (!block?.practice) fail(`catalogue ${entity.id}: scenario sans libelle.`);
    }
  }

  console.log(`Catalogue: ${catalog.entities.length} pratiques, ${categories.size} categories.`);
} catch (error) {
  fail(`practice-catalog.js: JSON CATALOG invalide: ${error.message}`);
}

if (warnings.length) {
  console.warn("Avertissements:");
  for (const message of warnings) console.warn(`- ${message}`);
}

if (errors.length) {
  console.error("Validation echouee:");
  for (const message of errors) console.error(`- ${message}`);
  process.exit(1);
}

console.log(`Validation OK${version ? ` (version ${version})` : ""}.`);
